### ISSUE TITLE
Too much BUG in your "train_cifar_ssl_acceleration.py"

### ISSUE THREAD

**Issue by z7d1** [Wakings/TABASCO#2]
#  RuntimeError: "nll_loss_forward_reduce_cuda_kernel_2d_index" not implemented for 'Int'
```python
labels = labels.type(torch.LongTensor) # should be inserted between line 124 and line 125.
```

![image](https://github.com/Wakings/TABASCO/assets/65475003/d3d94ff5-ca66-43f6-8467-e782343a33a4)

# RuntimeError: one_hot is only applicable to index tensor.

```python
# line 323 should be replaced:
jsd = weight * JS_dist(out, F.one_hot(target_var.to(torch.int64), num_classes=args.num_classes))
```
![image](https://github.com/Wakings/TABASCO/assets/65475003/03453c13-3e2e-4828-863a-7fc7b12178c8)

# RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

```python
select_index = select_index.cpu().numpy() #  should be inserted before line 238
```

![image](https://github.com/Wakings/TABASCO/assets/65475003/e4508353-dcd7-4096-8a1c-c0920da453ac)

# AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
```python
inputs_u, inputs_u2 = next(unlabeled_train_iter) # line 46 should be replaced 
```
![image](https://github.com/Wakings/TABASCO/assets/65475003/301018a3-9370-421c-963e-01e1c8e25fca)

**Comment by z7d1** [comment]
The PyTorch version I uesd:
```txt
pytorch                   2.2.2           py3.12_cuda12.1_cudnn8_0    pytorch
```

**Comment by Wakings** [comment]
Try it on Python3.6 and PyTorch 1.8.0, thanks.
